postprocessor:
  name: dpgmm_hierarchical
  APS_mode: False
  postprocessor_args:
    alpha: 1e-200
    max_cls_conf: False
    sigma0_scale: 1.
    sigma0_sample_cov: True
    kappa0: 1
    use_pca: True
    pca_dim: 256
    nu0_fixed: True
    nu0: 1000000
    gibbs_warmup: True
    gibbs_warmup_iters: 100
