postprocessor:
  name: dpgmm_spherical_mcc
  APS_mode: False
  postprocessor_args:
    alpha: 100.
    covariance_type: spherical
    estimate_hyperprior: False
    max_cls_conf: True
    sigma0_scale: 1.
