postprocessor:
  name: dpgmm_full
  APS_mode: False
  postprocessor_args:
    alpha: 1.
    covariance_type: full
    estimate_hyperprior: False
    max_cls_conf: False
    sigma0_scale: 1.
    kappa0: 1
