postprocessor:
  name: dpgmm_diag_hierarchical
  APS_mode: False
  postprocessor_args:
    alpha: 1e-200
    max_cls_conf: False
    sigma0_scale: 1.
    sigma0_sample_cov: True
    kappa0: 1
    use_pca: True
    pca_dim: 64
    nu0_fixed: False
    nu0: 100.
    gibbs_warmup: False
    gibbs_warmup_iters: 100
