postprocessor:
  name: dpgmm_hierarchical
  APS_mode: False
  postprocessor_args:
    alpha: 1e-200
    max_cls_conf: False
    sigma0_scale: 1.
    sigma0_sample_cov: True
    kappa0: 1
    use_pca: True
    pca_dim: 64
    nu0_fixed: False
    nu0: 1e6
    gibbs_warmup: False
    gibbs_warmup_iters: 10
    load_tied_covs: False
    tied_params_fname: 'tied_pca256.npz'
    use_likelihood: False
    init_sample_covs: False
