postprocessor:
  name: dpgmm
  APS_mode: True
  postprocessor_args:
    alpha: 1.
    covariance_type: spherical
    hierarchical: False
    estimate_hyperprior: False
    max_cls_conf: False
    sigma0_scale: 1.
    sigma0_sample_cov: True
    kappa0: 1.
  postprocessor_sweep:
    estimate_hyperprior_list: [False, True]
    sigma0_scale_list: [0.1, 1., 10., 100.]
    kappa0_list: [1, 10, 100]
