postprocessor:
  name: dpgmm_full
  APS_mode: False
  postprocessor_args:
    alpha: 1.
    covariance_type: full
    hierarchical: False
    estimate_hyperprior: False
    max_cls_conf: False
    sigma0_scale: 1.
    sigma0_sample_cov: True
    kappa0: 1
    use_pca: True
    pca_dim: 128
