postprocessor:
  name: dpgmm
  APS_mode: True
  postprocessor_args:
    alpha: 1.
    covariance_type: full
    max_cls_conf: False
    sigma0_scale: 1.
    sigma0_sample_cov: True
    kappa0: 1.
    use_pca: False
    pca_dim: 128
  postprocessor_sweep:
    sigma0_scale_list: [0.1, 1., 10., 100.]
    kappa0_list: [1, 10, 100]
